<?php

use App\Http\Controllers\Api\V1\AlertController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\CalendarController;
use App\Http\Controllers\Api\V1\DashboardController;
use App\Http\Controllers\Api\V1\DiscoveryController;
use App\Http\Controllers\Api\V1\ExportController;
use App\Http\Controllers\Api\V1\FriendInviteController;
use App\Http\Controllers\Api\V1\FriendshipController;
use App\Http\Controllers\Api\V1\InviteAcceptanceController;
use App\Http\Controllers\Api\V1\LibraryBrowserController;
use App\Http\Controllers\Api\V1\ManualLibraryController;
use App\Http\Controllers\Api\V1\MediaEventController;
use App\Http\Controllers\Api\V1\MediaListController;
use App\Http\Controllers\Api\V1\PlayerController;
use App\Http\Controllers\Api\V1\ProfileAvatarController;
use App\Http\Controllers\Api\V1\ProfileController;
use App\Http\Controllers\Api\V1\ProviderController;
use App\Http\Controllers\Api\V1\SettingsController;
use App\Http\Controllers\Api\V1\StatisticsController;
use App\Http\Controllers\Api\V1\StatusController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->middleware('web')->group(function (): void {
    Route::get('/status', StatusController::class);
    Route::post('/auth/login', [AuthController::class, 'login']);
    Route::post('/invites/accept', InviteAcceptanceController::class);
    Route::get('/profiles/search', [ProfileController::class, 'search'])->middleware(['auth', 'throttle:30,1,profile-search']);
    Route::get('/profiles/{user:profile_slug}', [ProfileController::class, 'show'])->middleware('throttle:60,1,profile-show');
    Route::get('/friend-invites/{token}', [FriendInviteController::class, 'show'])->middleware('throttle:30,1,friend-invite-show');

    Route::middleware('auth')->group(function (): void {
        Route::get('/me', [AuthController::class, 'me']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::get('/profile', [ProfileController::class, 'own']);
        Route::get('/profile/options', [ProfileController::class, 'options']);
        Route::patch('/profile', [ProfileController::class, 'update'])->middleware('throttle:6,60,profile-update');
        Route::post('/profile/avatar', [ProfileAvatarController::class, 'store'])->middleware('throttle:10,60,profile-avatar');
        Route::delete('/profile/avatar', [ProfileAvatarController::class, 'destroy'])->middleware('throttle:10,60,profile-avatar');
        Route::patch('/profile/privacy', [ProfileController::class, 'privacy'])->middleware('throttle:30,1,profile-privacy');
        Route::get('/profile/public-preview', [ProfileController::class, 'preview']);
        Route::get('/friends', [FriendshipController::class, 'index']);
        Route::get('/friends/requests', [FriendshipController::class, 'requests']);
        Route::post('/friends/request/{user:profile_slug}', [FriendshipController::class, 'requestFriend'])->middleware('throttle:10,1,friend-request');
        Route::post('/friends/{friendship}/accept', [FriendshipController::class, 'accept'])->middleware('throttle:20,1,friend-accept');
        Route::post('/friends/{friendship}/decline', [FriendshipController::class, 'decline'])->middleware('throttle:20,1,friend-decline');
        Route::delete('/friends/{friendship}', [FriendshipController::class, 'destroy']);
        Route::post('/friends/{user:profile_slug}/block', [FriendshipController::class, 'block'])->middleware('throttle:10,1,friend-block');
        Route::get('/friend-invites', [FriendInviteController::class, 'index']);
        Route::post('/friend-invites', [FriendInviteController::class, 'store'])->middleware('throttle:5,60,friend-invite-create');
        Route::post('/friend-invites/{token}/accept', [FriendInviteController::class, 'accept'])->middleware('throttle:10,1,friend-invite-accept');
        Route::delete('/friend-invites/{invite}', [FriendInviteController::class, 'destroy']);
        Route::get('/dashboard', DashboardController::class);
        Route::get('/calendar', CalendarController::class);
        Route::get('/stats', StatisticsController::class);
        Route::get('/settings', SettingsController::class);
        Route::get('/alerts', [AlertController::class, 'index']);
        Route::post('/alerts/{alert}/read', [AlertController::class, 'read']);
        Route::post('/alerts/read-all', [AlertController::class, 'readAll']);
        Route::get('/notification-preferences', [AlertController::class, 'preferences']);
        Route::patch('/notification-preferences', [AlertController::class, 'updatePreferences']);
        Route::get('/lists', [MediaListController::class, 'index']);
        Route::post('/lists', [MediaListController::class, 'store']);
        Route::get('/lists/{list}', [MediaListController::class, 'show']);
        Route::patch('/lists/{list}', [MediaListController::class, 'update']);
        Route::delete('/lists/{list}', [MediaListController::class, 'destroy']);
        Route::post('/lists/{list}/items', [MediaListController::class, 'addItem']);
        Route::delete('/lists/{list}/items/{item}', [MediaListController::class, 'removeItem']);
        Route::patch('/lists/{list}/reorder', [MediaListController::class, 'reorder']);
        Route::get('/exports/json', [ExportController::class, 'json'])->middleware('throttle:5,1');
        Route::get('/exports/csv/{dataset}', [ExportController::class, 'csv'])->middleware('throttle:10,1');
        Route::get('/media-events', [MediaEventController::class, 'index']);
        Route::get('/media-events/recent', [MediaEventController::class, 'recent']);
        Route::get('/library/movies', [LibraryBrowserController::class, 'movies']);
        Route::get('/library/shows', [LibraryBrowserController::class, 'shows']);
        Route::get('/library/history', [LibraryBrowserController::class, 'history']);
        Route::get('/library/search', [LibraryBrowserController::class, 'search']);
        Route::get('/library/movies/{movie}', [ManualLibraryController::class, 'showMovie']);
        Route::get('/library/shows/{show}', [ManualLibraryController::class, 'showShow']);
        Route::get('/library/episodes/{episode}', [ManualLibraryController::class, 'showEpisode']);
        Route::post('/library/movies/{movie}/watchlist', [ManualLibraryController::class, 'watchlistMovie']);
        Route::delete('/library/movies/{movie}/watchlist', [ManualLibraryController::class, 'removeMovieWatchlist']);
        Route::post('/library/shows/{show}/watchlist', [ManualLibraryController::class, 'watchlistShow']);
        Route::delete('/library/shows/{show}/watchlist', [ManualLibraryController::class, 'removeShowWatchlist']);
        Route::post('/library/shows/{show}/seasons/{season}/watch', [ManualLibraryController::class, 'watchSeason']);
        Route::delete('/library/shows/{show}/seasons/{season}/watch', [ManualLibraryController::class, 'unwatchSeason']);
        Route::post('/library/movies/{movie}/watch', [ManualLibraryController::class, 'watchMovie']);
        Route::post('/library/episodes/{episode}/watch', [ManualLibraryController::class, 'watchEpisode']);
        Route::delete('/library/movies/{movie}/watch', [ManualLibraryController::class, 'unwatchMovie']);
        Route::delete('/library/episodes/{episode}/watch', [ManualLibraryController::class, 'unwatchEpisode']);
        Route::post('/library/movies/{movie}/rating', [ManualLibraryController::class, 'rateMovie']);
        Route::post('/library/shows/{show}/rating', [ManualLibraryController::class, 'rateShow']);
        Route::post('/library/episodes/{episode}/rating', [ManualLibraryController::class, 'rateEpisode']);
        Route::delete('/library/movies/{movie}/rating', [ManualLibraryController::class, 'clearMovieRating']);
        Route::delete('/library/shows/{show}/rating', [ManualLibraryController::class, 'clearShowRating']);
        Route::delete('/library/episodes/{episode}/rating', [ManualLibraryController::class, 'clearEpisodeRating']);
        Route::post('/library/movies/{movie}/notes', [ManualLibraryController::class, 'noteMovie']);
        Route::post('/library/shows/{show}/notes', [ManualLibraryController::class, 'noteShow']);
        Route::post('/library/episodes/{episode}/notes', [ManualLibraryController::class, 'noteEpisode']);
        Route::patch('/library/notes/{note}', [ManualLibraryController::class, 'updateNote']);
        Route::delete('/library/notes/{note}', [ManualLibraryController::class, 'deleteNote']);
        Route::get('/discover/browse', [DiscoveryController::class, 'browse'])->middleware('throttle:30,1');
        Route::get('/discover/search', [DiscoveryController::class, 'search'])->middleware('throttle:30,1');
        Route::post('/discover/movies/{tmdbId}/add', [DiscoveryController::class, 'addMovie'])->middleware('throttle:30,1');
        Route::post('/discover/shows/{tmdbId}/add', [DiscoveryController::class, 'addShow'])->middleware('throttle:30,1');
        Route::get('/providers', [ProviderController::class, 'index']);
        Route::post('/providers/test', [ProviderController::class, 'test'])->middleware('throttle:10,1');
        Route::post('/providers', [ProviderController::class, 'store']);
        Route::patch('/providers/{provider}', [ProviderController::class, 'update']);
        Route::post('/providers/{provider}/refresh', [ProviderController::class, 'refresh'])->middleware('throttle:5,1');
        Route::delete('/providers/{provider}', [ProviderController::class, 'destroy']);
        Route::get('/player/sources', [PlayerController::class, 'sources']);
        Route::post('/player/sources', [PlayerController::class, 'storeSource']);
        Route::patch('/player/sources/{source}', [PlayerController::class, 'updateSource']);
        Route::delete('/player/sources/{source}', [PlayerController::class, 'destroySource']);
        Route::get('/player/items', [PlayerController::class, 'items']);
        Route::get('/player/catalog', [PlayerController::class, 'catalog']);
        Route::post('/player/sources/{source}/items', [PlayerController::class, 'storeItem']);
        Route::get('/player/link-targets', [PlayerController::class, 'linkTargets']);
        Route::post('/player/items/{item}/play', [PlayerController::class, 'play']);
        Route::patch('/player/items/{item}/favorite', [PlayerController::class, 'favorite']);
        Route::post('/player/items/{item}/ai-match', [PlayerController::class, 'aiMatch']);
        Route::post('/player/items/{item}/ai-match/reject', [PlayerController::class, 'rejectAiMatch']);
        Route::post('/player/items/{item}/link', [PlayerController::class, 'link']);
        Route::delete('/player/items/{item}/link', [PlayerController::class, 'unlink']);
        Route::patch('/player/sessions/{session}', [PlayerController::class, 'updateSession']);
    });
});
