import { useState } from "react";
import { apiRequest } from "../../lib/api.js";
import { Feedback, ResourceState, useAsyncAction, useResource } from "./shared.jsx";

export function MovieNights({ apiClient = apiRequest, onSessionExpired }) {
  const resource = useResource('/api/v1/movie-nights', apiClient, onSessionExpired);
  const settings = useResource('/api/v1/experience-settings', apiClient, onSessionExpired);
  const action = useAsyncAction(onSessionExpired);
  const [name, setName] = useState(''); const [roomId, setRoomId] = useState(null); const [friend, setFriend] = useState('');
  const [query, setQuery] = useState(''); const [results, setResults] = useState([]); const [selected, setSelected] = useState(null);
  const [message, setMessage] = useState(''); const [spoiler, setSpoiler] = useState(false);
  const data = resource.data || {}; const room = (data.rooms || []).find(item => item.id === roomId) || data.rooms?.[0];
  function save(path, method = 'POST', body, success = 'Saved.') { return action.run({ save: () => apiClient(path, { method, ...(body ? { body } : {}) }), refresh: resource.refresh, success }); }
  return <section className="v2-panel"><h3>Friends and movie nights</h3><ResourceState resource={resource} /><Feedback action={action} />
    <label><input type="checkbox" disabled={action.pending || settings.loading} checked={Boolean(settings.data?.settings?.share_activity)} onChange={e => action.run({ save: () => apiClient('/api/v1/experience-settings', { method: 'PATCH', body: { share_activity: e.target.checked } }), refresh: settings.refresh, success: 'Activity sharing updated.' })} />Share new watch activity with accepted friends</label><p>Sharing starts when you enable it. Turning it off hides your activity. Private notes and ratings stay private.</p>
    <details><summary>Recent friend activity</summary>{(data.activity || []).map(item => <p key={item.id}><strong>{item.name}</strong> watched {item.title} · {new Date(item.watchedAt).toLocaleDateString()}</p>)}{!data.activity?.length && <p>No shared activity yet.</p>}</details>
    <h4>Recommendations for you</h4>{(data.recommendations || []).map(item => <article className="v2-watch-row" key={item.id}><strong>{item.title}</strong><p>Recommended by {item.from}</p>{item.spoiler ? <details><summary>Reveal spoiler note</summary><p>{item.message}</p></details> : <p>{item.message}</p>}</article>)}
    {(data.invites || []).map(invite => <div className="v2-inline" key={invite.id}><span>Invitation: {invite.name}</span><button className="secondary-action" type="button" disabled={action.pending} onClick={() => save(`/api/v1/movie-nights/${invite.id}/join`)}>Join movie night</button><button className="text-action" type="button" disabled={action.pending} onClick={() => save(`/api/v1/movie-nights/${invite.id}`, 'DELETE')}>Decline</button></div>)}
    <form className="v2-inline" onSubmit={e => { e.preventDefault(); action.run({ save: () => apiClient('/api/v1/movie-nights', { method: 'POST', body: { name } }), onSaved: result => { setRoomId(result.id); setName(''); }, refresh: resource.refresh, success: 'Shared watchlist created. Invite a friend below.' }); }}><label>New movie night<input required maxLength={120} value={name} onChange={e => setName(e.target.value)} /></label><button className="secondary-action" disabled={action.pending}>Create movie night</button></form>
    <div className="v2-inline">{(data.rooms || []).map(item => <button className="text-action" type="button" key={item.id} onClick={() => setRoomId(item.id)}>{item.name}</button>)}</div>
    <label>Friend<select value={friend} onChange={e => setFriend(e.target.value)}><option value="">Choose an accepted friend</option>{(data.friends || []).map(item => <option key={item.slug} value={item.slug}>{item.name}</option>)}</select></label>
    {room && <div className="v2-panel"><h4>{room.name}</h4><p>{room.members.map(member => `${member.name}${member.accepted ? '' : ' (invited)'}`).join(', ') || 'Invite someone to choose together.'}</p><div className="v2-inline">{room.owner && <button className="secondary-action" type="button" disabled={!friend || action.pending} onClick={() => save(`/api/v1/movie-nights/${room.id}/invite`, 'POST', { slug: friend }, 'Invitation sent.')}>Invite selected friend</button>}<button className="text-action danger" type="button" disabled={action.pending} onClick={() => { if (window.confirm(room.owner ? 'Delete this movie night and its votes?' : 'Leave this movie night?')) save(`/api/v1/movie-nights/${room.id}`, 'DELETE'); }}>{room.owner ? 'Delete movie night' : 'Leave movie night'}</button></div>
      <div className="v2-queue">{room.titles.map((item, index) => <article key={item.id}><strong>{index === 0 && item.votes > 0 ? 'Top choice · ' : ''}{item.title}</strong><p>{item.votes} {item.votes === 1 ? "vote" : "votes"}</p><button className="secondary-action" disabled={action.pending} type="button" onClick={() => save(`/api/v1/movie-night-titles/${item.id}/vote`, 'POST', { vote: !item.myVote })}>{item.myVote ? 'Remove my vote' : 'Vote for this'}</button>{item.canRemove && <button className="text-action danger" type="button" disabled={action.pending} onClick={() => { if (window.confirm('Remove this suggestion and its votes?')) save(`/api/v1/movie-night-titles/${item.id}`, 'DELETE'); }}>Remove suggestion</button>}</article>)}</div>
    </div>}
    <form className="v2-inline" onSubmit={e => { e.preventDefault(); action.run({ save: () => apiClient(`/api/v1/library/search?query=${encodeURIComponent(query)}&type=all&limit=15`), onSaved: result => setResults([...(result.movies || []), ...(result.shows || [])]), success: 'Choose a title.' }); }}><label>Find a title to share<input minLength={2} required value={query} onChange={e => setQuery(e.target.value)} /></label><button className="secondary-action" disabled={action.pending}>Search titles</button></form><div className="v2-inline">{results.map(item => <button className="text-action" key={`${item.kind}-${item.id}`} type="button" onClick={() => setSelected(item)}>{item.title}</button>)}</div>
    {selected && <div className="v2-panel"><strong>{selected.title}</strong><div className="v2-inline">{room && <button className="secondary-action" type="button" disabled={action.pending} onClick={() => save(`/api/v1/movie-nights/${room.id}/titles`, 'POST', { type: selected.kind, media_id: selected.movieId || selected.showId || selected.id })}>Add to {room.name}</button>}</div><label>Recommendation note<textarea maxLength={1000} value={message} onChange={e => setMessage(e.target.value)} /></label><div className="v2-inline"><label><input type="checkbox" checked={spoiler} onChange={e => setSpoiler(e.target.checked)} />Contains spoilers</label><button className="primary-action" type="button" disabled={!friend || action.pending} onClick={() => save('/api/v1/friend-recommendations', 'POST', { slug: friend, type: selected.kind, media_id: selected.movieId || selected.showId || selected.id, message, spoiler }, 'Recommendation sent.')}>Recommend to selected friend</button></div></div>}
  </section>;
}
